export const posts = [
    "Activiteiten",
    "Bedrijvenrelaties",
    "Beheer",
    "Communicatie",
    "Cultuur",
    "Cursusdienst",
    "Development",
    "Fakbar",
    "Internationaal",
    "IT",
    "Logistiek",
    "Lustrum",
    "Onderwijs",
    "Praeses",
    "Secretaris",
    "Sport",
    "Theokot",
    "Vice-Praeses",
    "Ploeg",
    "Jaarwerking",
    "BEST",
    "Biomedix",
    "Chemix",
    "Existenz",
    "Statix",
    "IAESTE",
    "Mechanix",
    "Revue",
];

export const allowedEmailDomains = [
    "@vtk.be",
    "@bestleuven.eu",
    "@best-eu.org"
];