export const posts = [
    "Acti",
    "BR",
    "Beheer",
    "Commu",
    "Cultuur",
    "Cudi",
    "Dev",
    "Fakbar",
    "Internationaal",
    "IT",
    "Logi",
    "Lustrum",
    "Onderwijs",
    "Praeses",
    "Secretaris",
    "Sport",
    "Theokot",
    "Vice",
    "Ploeg",
    "Jaarwerking",
    "BEST",
    "Biomedix",
    "Chemix",
    "Existenz",
    "Statix",
    "IAESTE",
    "Mechanix",
    "Revue",
];

export const allowedEmailDomains = [
    "@vtk.be",
    "@bestleuven.eu",
    "@best-eu.org"
];